version: "3"
services:
  test:
    build: .
    volumes:
      - $PWD:/working
    container_name: yoda
    working_dir: /working
    ports:
      - 5431:5431
    environment:
      - PYTHONPATH=/working
    tty: true
